title: HRA O TR콡NY
baseURL: https://jovial-ptolemy-07956d.netlify.com/
languageCode: cs-cz
publishDir: public
googleAnalytics: UA-139430703-1
 <link rel="stylesheet" href="styles.css">

menu:
  main:
    - name: Domovsk치 str치nka
      url: /
      weight: 10
    - name: Archiv
      identifier: post
      url: /post/
      weight: 20

params:
  description: V na코em semestr치ln칤m projektu bychom 캜ten치콏콢m r치di p콏ibl칤쬴li kni쬹칤 i seri치lovou podobu p콏칤b캩hu, kter칳 si z칤skal srdce cel칠ho sv캩ta.
  authors: 游냨 Lucie Scholzov치, Terezie R칬ssov치, Tom치코 Badin
